In [134]:
#Install the dependencies
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib. pyplot as plt
import os

In [144]:
arr = []
with open("NASDAQ_ex.txt", "r") as filestream:
    for line in filestream:
        currentline = line.split(',')
        arr.append(currentline)
    stock_list = np.array(arr[0])


days = ['M', 'T', 'W', 'Th', 'F']
plt.clf()
for stock in stock_list:
    try:        
        print(stock)
        df = pd.read_csv("Stock_CSV/" + stock + '.csv') 
        df= df[['5. volume']]
        volumes = df.iloc[0:5].values
        result = volumes.ravel() 
        print(result)

        plt.bar(days, result, color = 'violet')
        plt.title('Average Volume per Day in Past Month')
        plt.xlabel('Days')
        plt.ylabel('Volume')
    #plt.show()

    
    
    # adding to plots_test folder
        plt.savefig('VOLUME_CHARTS/NASDAQ_volume_charts/' + stock + '.png')
        plt.clf()
    except pd.errors.EmptyDataError:
        print("Found empty file : {file}".format(file=file))
    # clears plot so that plots do not overlap on one plot
    #plt.clf()

AACG
[ 7119.  3908. 16506. 10304.  3009.]
AAL
[66854629. 54598512. 76320112. 49882258. 58984927.]
AAME
[30481.    94.  2775.  7644.   885.]
AAOI
[783352. 495949. 566763. 754950. 673295.]
AAPL
[31274973. 31203582. 29264342. 45247893. 32503750.]
AAWW
[493679. 612064. 743780. 800571. 546205.]
AAXJ
[ 652515. 1039207.  556157.  663091.  940476.]
AAXN
[ 815924.  502777.  341503.  849611. 1562435.]
ABCB
[600119. 363773. 241140. 360081. 340851.]
ABIO
[10696.  8799. 23212. 20914. 25770.]
ABMD
[600499. 443853. 328531. 391060. 342852.]
ABTX
[53787. 92886. 78512. 87309. 76976.]
ABUS
[331291. 489259. 199163. 498268. 756737.]
ACAD
[1068117. 1014156. 1206106. 1046230. 1949572.]
ACAMU
[  5.  99. 800. 291. 100.]
ACAMW
[3.70000e+01 1.00000e+00 2.68670e+04 5.00000e+03 1.66866e+05]
ACBI
[63555. 60836. 32105. 34644. 30323.]
ACER
[15643. 23626. 44740. 20793. 49861.]
ACGL
[1955796. 1509750. 1992008. 1998017. 1890332.]
ACGLP
[37819. 37977. 27734. 54025. 27120.]
ACHC
[808753. 575068. 494045. 771632. 554425.]
A

FileNotFoundError: [Errno 2] File Stock_CSV/AMTD.csv does not exist: 'Stock_CSV/AMTD.csv'

In [141]:
#days = ['M', 'T', 'W', 'Th', 'F']
#numbers = [1,2,3,4,5]

#plt.bar(days, numbers)
#plt.title('Average Volume per Day in Past Month for '+ stock)
#plt.xlabel('Days')
#plt.ylabel('Volume')
#plt.show()


In [ ]:
import glob

path = "Stock_CSV/*.csv"
for fname in glob.glob(path):
    third_to_fifth_chars = fname[10:len(fname)]
    print(third_to_fifth_chars)
    third_to_fifth_chars = third_to_fifth_chars[:len(third_to_fifth_chars)-4]
    print(third_to_fifth_chars)
    print(fname)

    df = pd.read_csv(fname) 
    df= df[['5. volume']]
    volumes = df.iloc[0:5].values
    result = volumes.ravel() 
    print(result)
    
    plt.bar(days, result, color = 'violet')
    plt.title(third_to_fifth_chars + ': Average Volume per Day in Past Month')
    plt.xlabel('Days')
    plt.ylabel('Volume')
    #plt.show()

    
    
    # adding to plots_test folder
    plt.savefig('VOLUME_CHARTS/NASDAQ_volume_charts/' + third_to_fifth_chars + '.png')
    plt.clf()

    

ANTE.csv
ANTE
Stock_CSV/ANTE.csv
[11106. 12354. 14564. 24204. 17031.]
CSCO.csv
CSCO
Stock_CSV/CSCO.csv
[14282137. 16100169. 18337406. 31661042. 23438799.]
LACQW.csv
LACQW
Stock_CSV/LACQW.csv
[ 3000.    70.  1000. 15000.   232.]
TOTA 2.csv
TOTA 2
Stock_CSV/TOTA 2.csv
[   0.    0.    0. 4003. 4600.]
HLNE.csv
HLNE
Stock_CSV/HLNE.csv
[ 71463. 139726. 104638.  96980.  73007.]
OCSI 2.csv
OCSI 2
Stock_CSV/OCSI 2.csv
[163765. 105270.  75638. 203197. 505638.]
PSM.csv
PSM
Stock_CSV/PSM.csv
[138.   1.   0.   0.   0.]
SBGI.csv
SBGI
Stock_CSV/SBGI.csv
[1164433. 2344052.  978157. 1594217. 1155276.]
UFCS.csv
UFCS
Stock_CSV/UFCS.csv
[39236. 77713. 51391. 50268. 53794.]
GFED.csv
GFED
Stock_CSV/GFED.csv
[5.6730e+03 6.4300e+02 6.8800e+02 9.0000e+00 1.4287e+04]
PAVMZ 2.csv
PAVMZ 2
Stock_CSV/PAVMZ 2.csv
[13900. 31400. 32209. 26067. 30904.]
AIRT.csv
AIRT
Stock_CSV/AIRT.csv
[2581.  155.  455. 1962. 3221.]
SUSC 2.csv
SUSC 2
Stock_CSV/SUSC 2.csv
[1107149.   67980.   32493.   27062.   24475.]
SMSI 2.csv
SMSI 2


VRAY.csv
VRAY
Stock_CSV/VRAY.csv
[1631140. 1432830.  742537. 1459818. 1338967.]
LOOP.csv
LOOP
Stock_CSV/LOOP.csv
[ 9742. 40402. 24053. 26966. 28523.]
CHY.csv
CHY
Stock_CSV/CHY.csv
[208417. 170290. 167248. 424305. 363375.]
TAYD.csv
TAYD
Stock_CSV/TAYD.csv
[2493. 5931. 1498. 4740. 6153.]
CREX.csv
CREX
Stock_CSV/CREX.csv
[ 1989. 13773.  7381.  1584.  9350.]
FYT.csv
FYT
Stock_CSV/FYT.csv
[ 4536.  4410.  9726.  3359. 23488.]
ACIU.csv
ACIU
Stock_CSV/ACIU.csv
[123769.  69231.  79669.  67070.  95772.]
XELA.csv
XELA
Stock_CSV/XELA.csv
[1013321. 3513235. 2189866. 1885446. 4054853.]
TATT.csv
TATT
Stock_CSV/TATT.csv
[ 281. 2284. 4100.  170. 1851.]
WSTG.csv
WSTG
Stock_CSV/WSTG.csv
[25009. 13095. 23885.  8940.  7529.]
ESPO.csv
ESPO
Stock_CSV/ESPO.csv
[ 84878.  65168.  71663. 120400. 173348.]
PFMT.csv
PFMT
Stock_CSV/PFMT.csv
[13936. 41644. 28973. 21716.  2954.]
SUPN 2.csv
SUPN 2
Stock_CSV/SUPN 2.csv
[491567. 625167. 450470. 479357. 436393.]
FYC.csv
FYC
Stock_CSV/FYC.csv
[26832. 13096. 17525. 21228. 1

MHLD.csv
MHLD
Stock_CSV/MHLD.csv
[593639. 448443. 357716. 459483. 201622.]
IEC.csv
IEC
Stock_CSV/IEC.csv
[12175. 17136. 23140.  3122. 41081.]
OIIM.csv
OIIM
Stock_CSV/OIIM.csv
[ 5788. 38201.  7509. 21421.  9271.]
SNDE 2.csv
SNDE 2
Stock_CSV/SNDE 2.csv
[1070706.   71475.   69191.   42213.   41195.]
APEI.csv
APEI
Stock_CSV/APEI.csv
[54822. 92904. 70351. 63622. 49503.]
TQQQ 2.csv
TQQQ 2
Stock_CSV/TQQQ 2.csv
[69162216. 64772516. 82251196. 64827148. 69310499.]
NERV 2.csv
NERV 2
Stock_CSV/NERV 2.csv
[269628. 227736. 354470. 299879. 472922.]
GLADL.csv
GLADL
Stock_CSV/GLADL.csv
[15332.  9428.  4582.  1100.  1184.]
PBBI.csv
PBBI
Stock_CSV/PBBI.csv
[ 8338. 36821. 33843. 10409. 48915.]
NXTD.csv
NXTD
Stock_CSV/NXTD.csv
[ 73196.  52172.  71865.  55420. 201091.]
MARK.csv
MARK
Stock_CSV/MARK.csv
[ 9484105.  4506499. 10463045.  8329795. 21507841.]
PACQU.csv
PACQU
Stock_CSV/PACQU.csv
[0. 0. 0. 0. 0.]
BPOP.csv
BPOP
Stock_CSV/BPOP.csv
[784347. 785637. 983681. 868929. 811899.]
NMRK 2.csv
NMRK 2
Stock_CSV/N

TRCH 2.csv
TRCH 2
Stock_CSV/TRCH 2.csv
[1352637.  245320.   70181.   89209.  100045.]
GNPX.csv
GNPX
Stock_CSV/GNPX.csv
[1354011. 3439807. 5123398. 1015099. 1381415.]
YTEN.csv
YTEN
Stock_CSV/YTEN.csv
[ 38337. 102211.  67355.  40428.  29753.]
AVGR.csv
AVGR
Stock_CSV/AVGR.csv
[700778. 358573. 197634. 272794. 197725.]
DLTH.csv
DLTH
Stock_CSV/DLTH.csv
[144214. 379122. 192158. 279231. 164710.]
RBBN.csv
RBBN
Stock_CSV/RBBN.csv
[485740. 378111. 568679. 373493. 437546.]
SAMAU.csv
SAMAU
Stock_CSV/SAMAU.csv
[0. 0. 0. 0. 0.]
PTEN 2.csv
PTEN 2
Stock_CSV/PTEN 2.csv
[9618380. 5643942. 9864210. 9229247. 7660692.]
ADXN.csv
ADXN
Stock_CSV/ADXN.csv
[3.000e+02 2.535e+03 0.000e+00 1.000e+00 1.010e+03]
ZCZZT.csv
ZCZZT
Stock_CSV/ZCZZT.csv
[100. 100. 100. 100. 100.]
ESGE.csv
ESGE
Stock_CSV/ESGE.csv
[1393886.  860848. 1028817. 1853316. 1559205.]
PSCF 2.csv
PSCF 2
Stock_CSV/PSCF 2.csv
[ 4785. 17052.  8911. 22749.  2901.]
ODT.csv
ODT
Stock_CSV/ODT.csv
[ 36843.  50869. 137571.  42400.  96458.]
MRAM 2.csv
MRAM 2
S

SIVBP 2.csv
SIVBP 2
Stock_CSV/SIVBP 2.csv
[80462. 72759. 35980. 25592. 19164.]
GENC.csv
GENC
Stock_CSV/GENC.csv
[10750. 24301. 13790. 22904. 19300.]
PTCT 2.csv
PTCT 2
Stock_CSV/PTCT 2.csv
[694105. 938894. 790707. 762112. 631880.]
BCOM.csv
BCOM
Stock_CSV/BCOM.csv
[ 6865. 11506.  2390.  4171. 10436.]
CLXT.csv
CLXT
Stock_CSV/CLXT.csv
[28818. 91062. 79576. 52519. 87081.]
CG.csv
CG
Stock_CSV/CG.csv
[ 858187.  996260. 1273289. 2294758. 1829534.]
CYAN.csv
CYAN
Stock_CSV/CYAN.csv
[1128. 4423. 1785. 2882. 2509.]
GLDI.csv
GLDI
Stock_CSV/GLDI.csv
[23251. 88893. 46633. 14682. 34161.]
SMTC 2.csv
SMTC 2
Stock_CSV/SMTC 2.csv
[684713. 535778. 737017. 664891. 544251.]
CNAT.csv
CNAT
Stock_CSV/CNAT.csv
[  93353.  148297.  212099.  379733. 3212891.]
NVFY 2.csv
NVFY 2
Stock_CSV/NVFY 2.csv
[11441.  4090.  1920.  3047.  1233.]
CBTX.csv
CBTX
Stock_CSV/CBTX.csv
[26250. 41248. 43180. 39665. 42416.]
WASH.csv
WASH
Stock_CSV/WASH.csv
[ 81434.  93830.  83910.  91712. 124989.]
TOWN 2.csv
TOWN 2
Stock_CSV/TOWN 2.csv


EVSIW.csv
EVSIW
Stock_CSV/EVSIW.csv
[ 5165.  2200. 12089.   362. 21207.]
SXTC 2.csv
SXTC 2
Stock_CSV/SXTC 2.csv
[568665. 484988. 649266. 706505. 480317.]
LACQU.csv
LACQU
Stock_CSV/LACQU.csv
[0. 0. 0. 0. 0.]
AVGOP.csv
AVGOP
Stock_CSV/AVGOP.csv
[ 3446.  3994.  4490. 67883. 26049.]
IBKCN.csv
IBKCN
Stock_CSV/IBKCN.csv
[14085. 19895. 22478. 28296.  6852.]
RFAP.csv
RFAP
Stock_CSV/RFAP.csv
[ 1158.  1865. 15186.  2670.   426.]
PETQ 2.csv
PETQ 2
Stock_CSV/PETQ 2.csv
[274218. 384284. 405682. 317535. 238534.]
PTVCB.csv
PTVCB
Stock_CSV/PTVCB.csv
[28941. 44145. 12113. 10627. 15113.]
FLMN.csv
FLMN
Stock_CSV/FLMN.csv
[196484. 273724. 204790. 231769. 235824.]
MCEP.csv
MCEP
Stock_CSV/MCEP.csv
[898398. 328200. 254841. 123374.  99167.]
SRCL.csv
SRCL
Stock_CSV/SRCL.csv
[951624. 468491. 483933. 586834. 632354.]
DFPHU.csv
DFPHU
Stock_CSV/DFPHU.csv
[5.56720e+04 1.70000e+01 1.43835e+05 5.01780e+04 1.70560e+04]
HCAPZ.csv
HCAPZ
Stock_CSV/HCAPZ.csv
[4207. 2191. 1179.  230.  790.]
SONGW.csv
SONGW
Stock_CSV/SONGW.

ATRC.csv
ATRC
Stock_CSV/ATRC.csv
[589178. 854291. 260372. 240789. 235932.]
BSJN.csv
BSJN
Stock_CSV/BSJN.csv
[296564. 313757. 222416. 381152. 273400.]
UEIC.csv
UEIC
Stock_CSV/UEIC.csv
[58920. 83756. 36172. 52586. 51204.]
PRGX 2.csv
PRGX 2
Stock_CSV/PRGX 2.csv
[ 28503.  34056. 105507.  56573.  39110.]
XNET.csv
XNET
Stock_CSV/XNET.csv
[168464. 358998. 454076. 607001. 482913.]
JRSH.csv
JRSH
Stock_CSV/JRSH.csv
[ 484.   93. 1327.  979.  297.]
VETS.csv
VETS
Stock_CSV/VETS.csv
[ 15.   7.   0. 620.  15.]
VLGEA.csv
VLGEA
Stock_CSV/VLGEA.csv
[71225. 87177. 60897. 60071. 59471.]
GWPH.csv
GWPH
Stock_CSV/GWPH.csv
[270679. 165645. 176111. 396982. 409239.]
F.csv
F
Stock_CSV/F.csv
[1.06239953e+08 1.38212065e+08 1.98655076e+08 1.45754989e+08
 1.34826921e+08]
FAT.csv
FAT
Stock_CSV/FAT.csv
[6435. 4856. 5849. 8295. 2423.]
ECOW.csv
ECOW
Stock_CSV/ECOW.csv
[ 220. 7423.    0.    0.   12.]
NBLX 2.csv
NBLX 2
Stock_CSV/NBLX 2.csv
[1566949.  852655. 1058382.  732896.  533908.]
TZOO.csv
TZOO
Stock_CSV/TZOO.csv
[18

SLS 2.csv
SLS 2
Stock_CSV/SLS 2.csv
[104451. 207292.  91854. 130726. 126891.]
QRTEA.csv
QRTEA
Stock_CSV/QRTEA.csv
[2030031. 3299936. 2244635. 2831927. 3349948.]
SHV 2.csv
SHV 2
Stock_CSV/SHV 2.csv
[6619901. 4077975. 4795003. 3622369. 7686885.]
WTFC.csv
WTFC
Stock_CSV/WTFC.csv
[ 662589.  739101. 1503883.  795085.  888504.]
TFFP.csv
TFFP
Stock_CSV/TFFP.csv
[42028. 55003. 83898. 39285. 18901.]
BRPAW.csv
BRPAW
Stock_CSV/BRPAW.csv
[    0.  1150. 14750.   101.  2602.]
BDGE.csv
BDGE
Stock_CSV/BDGE.csv
[40468. 66785. 83965. 75174. 63466.]
RTTR 2.csv
RTTR 2
Stock_CSV/RTTR 2.csv
[3416601. 3947560. 3638336. 3070920. 3363059.]
RBCN.csv
RBCN
Stock_CSV/RBCN.csv
[11115. 11098.  3231.  1930. 16294.]
GBDC.csv
GBDC
Stock_CSV/GBDC.csv
[1148357.  750286. 1032122.  927745.  837987.]
LAZY.csv
LAZY
Stock_CSV/LAZY.csv
[2499. 2772. 1474. 1857. 1288.]
GHIVU.csv
GHIVU
Stock_CSV/GHIVU.csv
[  8452.   5348. 627071. 135369. 261374.]
DPHCU.csv
DPHCU
Stock_CSV/DPHCU.csv
[0. 0. 0. 1. 0.]
DWCR.csv
DWCR
Stock_CSV/DWCR.cs

OPRA.csv
OPRA
Stock_CSV/OPRA.csv
[230245. 527996. 186973. 164250. 554040.]
KURA.csv
KURA
Stock_CSV/KURA.csv
[188641. 189165. 145305. 163542. 164589.]
LSXMK.csv
LSXMK
Stock_CSV/LSXMK.csv
[2199065. 4223579. 1003250.  640799. 1089242.]
ALAC.csv
ALAC
Stock_CSV/ALAC.csv
[6.00000e+00 2.86000e+02 1.50015e+05 1.51000e+02 1.10800e+04]
VOXX.csv
VOXX
Stock_CSV/VOXX.csv
[121627. 222570. 253850. 231912. 208726.]
MDLZ.csv
MDLZ
Stock_CSV/MDLZ.csv
[7989978. 5820856. 9592544. 9426764. 7788484.]
ZIXI.csv
ZIXI
Stock_CSV/ZIXI.csv
[ 712924. 2402663. 1797195. 2138136. 1149371.]
BNDW.csv
BNDW
Stock_CSV/BNDW.csv
[20400. 13150. 36349. 20697. 27308.]
BBH.csv
BBH
Stock_CSV/BBH.csv
[24820. 40109. 53691. 33299. 81561.]
NFIN.csv
NFIN
Stock_CSV/NFIN.csv
[1.06905e+05 7.41000e+02 2.00000e+00 1.46772e+05 2.62000e+02]
XBIOW.csv
XBIOW
Stock_CSV/XBIOW.csv
[   0.    0. 2918.    0.    0.]
SPAR.csv
SPAR
Stock_CSV/SPAR.csv
[149813. 222535. 352625. 233423. 177236.]
IEP.csv
IEP
Stock_CSV/IEP.csv
[154559. 146838. 110763. 126311.

VRNS.csv
VRNS
Stock_CSV/VRNS.csv
[343681. 308635. 290488. 340726. 240783.]
JBLU.csv
JBLU
Stock_CSV/JBLU.csv
[11152785. 13810233. 15149147.  9618557. 11278954.]
OBAS 2.csv
OBAS 2
Stock_CSV/OBAS 2.csv
[    0.     0. 11100.  6480.     0.]
MSVB 2.csv
MSVB 2
Stock_CSV/MSVB 2.csv
[3707. 8293.  313. 2525. 1300.]
PRPL 2.csv
PRPL 2
Stock_CSV/PRPL 2.csv
[483407. 340026. 458579. 498305. 431992.]
SBT.csv
SBT
Stock_CSV/SBT.csv
[113586. 102352.  34681.  43217.  30782.]
RUTH.csv
RUTH
Stock_CSV/RUTH.csv
[1047689.  880707. 1265737. 1020494. 1428987.]
PTSI.csv
PTSI
Stock_CSV/PTSI.csv
[5885. 3658. 7396. 6999. 1843.]
DGRE.csv
DGRE
Stock_CSV/DGRE.csv
[37604. 13044. 16723. 10318.  6377.]
TTNP.csv
TTNP
Stock_CSV/TTNP.csv
[7228406. 2721260. 2701099. 3119599. 3848948.]
TLC 2.csv
TLC 2
Stock_CSV/TLC 2.csv
[ 435. 2934. 1707. 5244. 2069.]
HTHT.csv
HTHT
Stock_CSV/HTHT.csv
[1403098. 2294429. 2324422. 1838036. 1987663.]
RBCAA 2.csv
RBCAA 2
Stock_CSV/RBCAA 2.csv
[40523. 36488. 51217. 36473. 42995.]
PNNT 2.csv
PNNT 2


ARPO.csv
ARPO
Stock_CSV/ARPO.csv
[ 707614.  416693.  224529.  578629. 1139970.]
ICLN.csv
ICLN
Stock_CSV/ICLN.csv
[ 447294.  383338.  540720. 1355949.  446782.]
SCWX 2.csv
SCWX 2
Stock_CSV/SCWX 2.csv
[101229.  86598. 197711. 113541.  90889.]
DCPH.csv
DCPH
Stock_CSV/DCPH.csv
[392397. 456110. 262810. 419847. 483202.]
BPTH.csv
BPTH
Stock_CSV/BPTH.csv
[186570.  86009.  70706.  62813.  93592.]
CDTX.csv
CDTX
Stock_CSV/CDTX.csv
[285193. 174958.  75781. 138919. 239957.]
IMMR.csv
IMMR
Stock_CSV/IMMR.csv
[187703. 260361. 226791. 313270. 232549.]
MOHO.csv
MOHO
Stock_CSV/MOHO.csv
[41864. 38707. 39059. 41194. 39823.]
IEF.csv
IEF
Stock_CSV/IEF.csv
[2373175. 2346265. 3168690. 3287659. 4230725.]
ESQ.csv
ESQ
Stock_CSV/ESQ.csv
[24122. 35293. 24618. 28431. 38448.]
IHRT.csv
IHRT
Stock_CSV/IHRT.csv
[757007. 810302. 516355. 724003. 365583.]
PFBI 2.csv
PFBI 2
Stock_CSV/PFBI 2.csv
[22778. 21802. 23153. 31473. 52805.]
NSEC.csv
NSEC
Stock_CSV/NSEC.csv
[  9. 112.   0. 512.  30.]
USAP.csv
USAP
Stock_CSV/USAP.csv
[

SMPL.csv
SMPL
Stock_CSV/SMPL.csv
[ 670645. 1313478. 1167373. 1113466. 1070836.]
INTU.csv
INTU
Stock_CSV/INTU.csv
[1069878. 1309228. 1258667. 1525759. 1297402.]
JFKKW.csv
JFKKW
Stock_CSV/JFKKW.csv
[2.2000e+02 6.0000e+04 7.3000e+01 4.0000e+01 2.3007e+04]
GRFS.csv
GRFS
Stock_CSV/GRFS.csv
[ 571348.  883403.  411211. 1438715.  499262.]
SLMBP 2.csv
SLMBP 2
Stock_CSV/SLMBP 2.csv
[13172.  3739.  4546.  6175.  7977.]
BSCS.csv
BSCS
Stock_CSV/BSCS.csv
[16569. 19698. 11836. 16910. 20808.]
FTXL.csv
FTXL
Stock_CSV/FTXL.csv
[  6865.   9627.   5625.   5412. 130477.]
MNKD.csv
MNKD
Stock_CSV/MNKD.csv
[1129668. 1423300. 1422468. 1086479. 1576003.]
HA.csv
HA
Stock_CSV/HA.csv
[ 974586. 1141799. 1128121.  876865. 1042450.]
UBFO.csv
UBFO
Stock_CSV/UBFO.csv
[15737. 21895. 22041.  9713. 30228.]
TLRY 2.csv
TLRY 2
Stock_CSV/TLRY 2.csv
[26388906. 20631495. 55330606. 70595163. 26072998.]
PLL 2.csv
PLL 2
Stock_CSV/PLL 2.csv
[15199.   953.  4240.  6893.  4458.]
LASR.csv
LASR
Stock_CSV/LASR.csv
[106248. 190888. 12911

RP 2.csv
RP 2
Stock_CSV/RP 2.csv
[ 831024.  544758.  619650. 1146675. 1718595.]
PAVM.csv
PAVM
Stock_CSV/PAVM.csv
[607825. 522520. 990369. 792062. 441394.]
GO.csv
GO
Stock_CSV/GO.csv
[3148769. 8662140. 3066390. 1521331.  935165.]
VRRM.csv
VRRM
Stock_CSV/VRRM.csv
[2123181. 1003709. 1464321. 1242758. 1454269.]
DGLD.csv
DGLD
Stock_CSV/DGLD.csv
[223319. 139860. 269038. 282158. 220355.]
THCA.csv
THCA
Stock_CSV/THCA.csv
[200.   0.   0.   0.   0.]
CRVL.csv
CRVL
Stock_CSV/CRVL.csv
[46972. 46144. 55240. 51842. 68503.]
LFVN.csv
LFVN
Stock_CSV/LFVN.csv
[32202. 56844. 26492. 49734. 66109.]
IRIX.csv
IRIX
Stock_CSV/IRIX.csv
[16512. 13560. 10551. 29513. 64021.]
PCOM.csv
PCOM
Stock_CSV/PCOM.csv
[27897. 56500. 54984. 42797. 49059.]
ESLT.csv
ESLT
Stock_CSV/ESLT.csv
[37269. 37147. 27831. 41741. 36772.]
INTC.csv
INTC
Stock_CSV/INTC.csv
[50068813. 35091952. 23443745. 25248033. 26420309.]
FITBI.csv
FITBI
Stock_CSV/FITBI.csv
[20024. 19394. 18104. 40005. 34868.]
SAQNU 2.csv
SAQNU 2
Stock_CSV/SAQNU 2.csv
[     

RNEM 2.csv
RNEM 2
Stock_CSV/RNEM 2.csv
[ 764. 2081.  312.  322.  268.]
EPIX.csv
EPIX
Stock_CSV/EPIX.csv
[12309. 10818. 17367. 10730. 37822.]
LOACU.csv
LOACU
Stock_CSV/LOACU.csv
[0. 0. 0. 0. 0.]
MDJH.csv
MDJH
Stock_CSV/MDJH.csv
[ 739.    5. 1096. 1452. 1112.]
KLXE.csv
KLXE
Stock_CSV/KLXE.csv
[3311536. 6007988.  601622.  785163. 1064068.]
KBWR.csv
KBWR
Stock_CSV/KBWR.csv
[ 1249. 10504.  2161.   863.  5857.]
PGNX.csv
PGNX
Stock_CSV/PGNX.csv
[ 583356.  967595.  972924. 1081415.  763614.]
SPPI.csv
SPPI
Stock_CSV/SPPI.csv
[ 765613.  891526. 1645508. 1186814. 1419493.]
GAIA.csv
GAIA
Stock_CSV/GAIA.csv
[ 96448.  65807. 173961. 153649. 156292.]
MCMJ.csv
MCMJ
Stock_CSV/MCMJ.csv
[2728.  382.  408. 1056. 3374.]
SLVO.csv
SLVO
Stock_CSV/SLVO.csv
[12093.  2926. 22689. 14495. 36825.]
CRSAW.csv
CRSAW
Stock_CSV/CRSAW.csv
[   0.    5.  100.  100. 1772.]
PRCP.csv
PRCP
Stock_CSV/PRCP.csv
[28779. 20716. 13109. 16734. 34629.]
DMTK.csv
DMTK
Stock_CSV/DMTK.csv
[ 8371. 14368. 12958. 20189. 41000.]
IDCC.csv
IDCC

SDG.csv
SDG
Stock_CSV/SDG.csv
[33203.  5562.  6819.  9695. 13287.]
DWSN.csv
DWSN
Stock_CSV/DWSN.csv
[26610. 39133. 22277. 59449.  9833.]
KVHI.csv
KVHI
Stock_CSV/KVHI.csv
[124410.  32525.  20219.  99134.  34831.]
MELI.csv
MELI
Stock_CSV/MELI.csv
[713702. 429297. 669957. 546844. 550706.]
LOGM.csv
LOGM
Stock_CSV/LOGM.csv
[585446. 351884. 501177. 730926. 759561.]
FTNT.csv
FTNT
Stock_CSV/FTNT.csv
[1294400. 2372609. 1279555. 3585025. 1529556.]
NUVA.csv
NUVA
Stock_CSV/NUVA.csv
[1534776. 1745175. 1575539. 1672057.  721579.]
RNDV.csv
RNDV
Stock_CSV/RNDV.csv
[16782.  1720.  5595.  4806.  1561.]
OMAB.csv
OMAB
Stock_CSV/OMAB.csv
[113869.  46545. 164190. 206815. 156248.]
AMAG.csv
AMAG
Stock_CSV/AMAG.csv
[399022. 450604. 476284. 587123. 729017.]
SAFT 2.csv
SAFT 2
Stock_CSV/SAFT 2.csv
[56034. 60147. 58880. 56826. 53086.]
IGIC.csv
IGIC
Stock_CSV/IGIC.csv
[18983. 19264. 25272. 26232. 19537.]
TPTX 2.csv
TPTX 2
Stock_CSV/TPTX 2.csv
[301343. 203718. 452225. 392268. 323439.]
AMCX.csv
AMCX
Stock_CSV/AMCX.cs

HBIO.csv
HBIO
Stock_CSV/HBIO.csv
[140041. 273238. 106367. 163799. 152282.]
SPOK 2.csv
SPOK 2
Stock_CSV/SPOK 2.csv
[136355.  60864.  84866. 171246. 156307.]
ORSNW.csv
ORSNW
Stock_CSV/ORSNW.csv
[  489. 36687.  1200.  1195.  1690.]
ZGYHU.csv
ZGYHU
Stock_CSV/ZGYHU.csv
[ 2702.  1109. 25512. 16628. 23318.]
SRET 2.csv
SRET 2
Stock_CSV/SRET 2.csv
[1504624.  720048. 1563915. 1116350.  777256.]
NAII 2.csv
NAII 2
Stock_CSV/NAII 2.csv
[ 5919.   664.  2090. 22015.  3402.]
NVIV.csv
NVIV
Stock_CSV/NVIV.csv
[ 915927.  820290.  487363.  906537. 1341173.]
GOODN.csv
GOODN
Stock_CSV/GOODN.csv
[10959. 25014.  6634.  1835.  4949.]
NMRK.csv
NMRK
Stock_CSV/NMRK.csv
[1268750. 1539372. 1319532. 1494156. 1492117.]
PSCE 2.csv
PSCE 2
Stock_CSV/PSCE 2.csv
[101509. 116666. 102364.  55654.  47688.]
MCBS.csv
MCBS
Stock_CSV/MCBS.csv
[31036. 21675. 27690. 42295. 29861.]
TOUR 2.csv
TOUR 2
Stock_CSV/TOUR 2.csv
[90234. 48295. 73453. 29498. 17630.]
PAACR.csv
PAACR
Stock_CSV/PAACR.csv
[  600. 30000.  4902. 30300. 10000.]
BPF

OTTR.csv
OTTR
Stock_CSV/OTTR.csv
[ 91217. 105602. 194185. 107048. 104934.]
GPRE.csv
GPRE
Stock_CSV/GPRE.csv
[249298. 343229. 396926. 421464. 581917.]
THBR 2.csv
THBR 2
Stock_CSV/THBR 2.csv
[1.955000e+03 0.000000e+00 2.455886e+06 8.324600e+04 2.000000e+01]
OCUL.csv
OCUL
Stock_CSV/OCUL.csv
[690611. 486934. 615776. 903792. 745886.]
TCRD.csv
TCRD
Stock_CSV/TCRD.csv
[108115. 170154. 247687. 157832. 280578.]
ACN.csv
ACN
Stock_CSV/ACN.csv
[3802436. 5194360. 4795480. 4684046. 6173727.]
GH.csv
GH
Stock_CSV/GH.csv
[ 906489.  474366.  683875.  676348. 1147512.]
ADPT.csv
ADPT
Stock_CSV/ADPT.csv
[ 771876. 1298771.  874864.  526649.  921737.]
YMAB.csv
YMAB
Stock_CSV/YMAB.csv
[202933. 155659. 148992. 154474. 168378.]
KERNW.csv
KERNW
Stock_CSV/KERNW.csv
[83992. 36678.  8406.  2750. 39441.]
PFSW.csv
PFSW
Stock_CSV/PFSW.csv
[ 12023.  36987. 956626.   6983.  25783.]
OXBR.csv
OXBR
Stock_CSV/OXBR.csv
[6285. 3108. 1738. 8456. 7108.]
AMTBB.csv
AMTBB
Stock_CSV/AMTBB.csv
[558. 472. 868. 834. 212.]
GLIBA.csv
GL

SMRT.csv
SMRT
Stock_CSV/SMRT.csv
[2076264. 2650906.  720890. 1169769. 3075156.]
AACG.csv
AACG
Stock_CSV/AACG.csv
[ 7119.  3908. 16506. 10304.  3009.]
SPG.csv
SPG
Stock_CSV/SPG.csv
[ 4836806.  8728656.  8656000.  7398571. 10674614.]
EMKR.csv
EMKR
Stock_CSV/EMKR.csv
[50048. 50630. 25573. 54857. 96623.]
PSEC.csv
PSEC
Stock_CSV/PSEC.csv
[2616026. 3169092. 1982281. 4676937. 4472806.]
MIME.csv
MIME
Stock_CSV/MIME.csv
[ 559365. 1247030.  899491.  907049.  874821.]
AMD.csv
AMD
Stock_CSV/AMD.csv
[7.2518203e+07 6.9662688e+07 6.3164076e+07 1.2390639e+08 7.2367258e+07]
XPER.csv
XPER
Stock_CSV/XPER.csv
[271899. 423199. 292881. 289591. 557117.]
IMRNW.csv
IMRNW
Stock_CSV/IMRNW.csv
[1.200e+01 2.919e+03 6.609e+03 4.000e+00 8.300e+01]
SBCF 2.csv
SBCF 2
Stock_CSV/SBCF 2.csv
[297972. 390094. 419193. 203208. 381475.]
GNUS.csv
GNUS
Stock_CSV/GNUS.csv
[ 439420.  388041.  491749.  925963. 5959504.]
NOVN 2.csv
NOVN 2
Stock_CSV/NOVN 2.csv
[ 3731001.  5247470.  4025215.  4626295. 15312858.]
FITBO.csv
FITBO
Stock

MRKR 2.csv
MRKR 2
Stock_CSV/MRKR 2.csv
[222538. 250564. 241342. 171790. 178025.]
BFC.csv
BFC
Stock_CSV/BFC.csv
[3891. 7631. 5481. 3525. 6705.]
CCNE.csv
CCNE
Stock_CSV/CCNE.csv
[26510. 48958. 43719. 66159. 77426.]
BRQS.csv
BRQS
Stock_CSV/BRQS.csv
[ 409659.  893660.   93471.  273805. 1480251.]
RVMD 2.csv
RVMD 2
Stock_CSV/RVMD 2.csv
[138373. 262388. 236484. 170184. 372470.]
YNDX.csv
YNDX
Stock_CSV/YNDX.csv
[1669492. 1095629. 1896122. 4170287. 3854840.]
ADILW.csv
ADILW
Stock_CSV/ADILW.csv
[4417.  510.  704.   80. 1380.]
LGIH.csv
LGIH
Stock_CSV/LGIH.csv
[405353. 348054. 459390. 247076. 490626.]
APVO.csv
APVO
Stock_CSV/APVO.csv
[74579. 48361. 45910. 41609. 23916.]
THCB 2.csv
THCB 2
Stock_CSV/THCB 2.csv
[7.00000e+02 9.00000e+00 1.09831e+05 1.01465e+05 5.70300e+03]
SPSC.csv
SPSC
Stock_CSV/SPSC.csv
[283082. 250856. 193561. 282226. 223909.]
FBIZ.csv
FBIZ
Stock_CSV/FBIZ.csv
[28049. 13699. 17188. 26580. 35552.]
VVPR.csv
VVPR
Stock_CSV/VVPR.csv
[ 6659. 31412. 32019. 11344. 19935.]
PRTH.csv
PRTH
Sto

RETA.csv
RETA
Stock_CSV/RETA.csv
[165884. 214055. 283650. 292079. 367866.]
ZIONL.csv
ZIONL
Stock_CSV/ZIONL.csv
[41606.  7526. 38411. 16191.  9812.]
IPKW.csv
IPKW
Stock_CSV/IPKW.csv
[16208. 60182. 11632.  7873. 22783.]
AMCI.csv
AMCI
Stock_CSV/AMCI.csv
[79981.   475.  1356.   961.   891.]
CRNX.csv
CRNX
Stock_CSV/CRNX.csv
[144560. 254146. 220686. 142721. 160101.]
NBTB.csv
NBTB
Stock_CSV/NBTB.csv
[119638. 138283. 131221. 123806. 172972.]
DWSH.csv
DWSH
Stock_CSV/DWSH.csv
[241281. 340207. 139938. 225117. 279683.]
SMCP 2.csv
SMCP 2
Stock_CSV/SMCP 2.csv
[   0.    0. 3800.    0.    0.]
RNET.csv
RNET
Stock_CSV/RNET.csv
[665109. 484400. 737536. 356076. 429999.]
SATS 2.csv
SATS 2
Stock_CSV/SATS 2.csv
[367484. 472285. 746344. 662199. 720806.]
SANW 2.csv
SANW 2
Stock_CSV/SANW 2.csv
[17235. 19805. 17950. 12884.  5844.]
FMCIU.csv
FMCIU
Stock_CSV/FMCIU.csv
[   0. 5032.    0.    0.    0.]
GNMA.csv
GNMA
Stock_CSV/GNMA.csv
[ 96553.  30153. 268735.  34769.  40107.]
PT.csv
PT
Stock_CSV/PT.csv
[239207. 27224

KOD.csv
KOD
Stock_CSV/KOD.csv
[256824. 251310. 222607. 202803. 240202.]
TLGT 2.csv
TLGT 2
Stock_CSV/TLGT 2.csv
[ 361883. 1001726.  676820.  106779.  157233.]
AGBAW.csv
AGBAW
Stock_CSV/AGBAW.csv
[    0.  1400. 76826.   100.   333.]
KBWB.csv
KBWB
Stock_CSV/KBWB.csv
[179435. 235904. 392768. 923816. 331260.]
BRPA.csv
BRPA
Stock_CSV/BRPA.csv
[  0. 100.   0.   0.   0.]
FEMB.csv
FEMB
Stock_CSV/FEMB.csv
[46293. 61409. 89863. 52962. 92014.]
NBTB 2.csv
NBTB 2
Stock_CSV/NBTB 2.csv
[141070. 135590. 192196. 219272. 228856.]
UFO.csv
UFO
Stock_CSV/UFO.csv
[20000.  3255.  6318.  5284.  5389.]
TFSL 2.csv
TFSL 2
Stock_CSV/TFSL 2.csv
[239848. 246668. 179597. 352141. 365824.]
BWMX.csv
BWMX
Stock_CSV/BWMX.csv
[0.000e+00 3.205e+03 1.000e+00 0.000e+00 2.763e+03]
GXGX.csv
GXGX
Stock_CSV/GXGX.csv
[  500.   200.   743. 24680.   430.]
CATH.csv
CATH
Stock_CSV/CATH.csv
[ 6943. 17166.  3174.  6514. 76253.]
MTLS.csv
MTLS
Stock_CSV/MTLS.csv
[57774. 44705. 53203. 76723. 60880.]
CHEKZ.csv
CHEKZ
Stock_CSV/CHEKZ.csv
[261

OVLY.csv
OVLY
Stock_CSV/OVLY.csv
[ 8387. 15250. 11844. 19022.  8441.]
CETV.csv
CETV
Stock_CSV/CETV.csv
[255778. 852739. 634321. 259181. 403338.]
FEP.csv
FEP
Stock_CSV/FEP.csv
[336983.  80937.  60535.  87136.  72995.]
POPE 2.csv
POPE 2
Stock_CSV/POPE 2.csv
[19374. 40706. 26108. 15616.  4086.]
SNGX 2.csv
SNGX 2
Stock_CSV/SNGX 2.csv
[ 260292.  196328.  243449.  508608. 1397015.]
FANG.csv
FANG
Stock_CSV/FANG.csv
[5351744. 5175779. 4616648. 4822518. 4717719.]
PCYG 2.csv
PCYG 2
Stock_CSV/PCYG 2.csv
[ 67463.  50178.  36923. 121912.  78464.]
TAIT.csv
TAIT
Stock_CSV/TAIT.csv
[4326. 3080. 2076. 3718. 1386.]
CBPO.csv
CBPO
Stock_CSV/CBPO.csv
[83601. 58533. 42399. 43747. 89290.]
EARS.csv
EARS
Stock_CSV/EARS.csv
[284260.  51624.  76743.  46240.  66593.]
FDT.csv
FDT
Stock_CSV/FDT.csv
[ 67464. 116535. 105532. 168658.  94243.]
CRVS.csv
CRVS
Stock_CSV/CRVS.csv
[80023. 64599. 80577. 60790. 55361.]
KMDA.csv
KMDA
Stock_CSV/KMDA.csv
[ 27162.  16192.  50598. 110663.  49273.]
BSMQ.csv
BSMQ
Stock_CSV/BSMQ.csv


MYT.csv
MYT
Stock_CSV/MYT.csv
[17726. 30672. 15235. 91466. 47912.]
KE.csv
KE
Stock_CSV/KE.csv
[48182. 89286. 62587. 56119. 45916.]
GNTX.csv
GNTX
Stock_CSV/GNTX.csv
[2818602. 2170583. 2048250. 1687411. 2397858.]
REAL.csv
REAL
Stock_CSV/REAL.csv
[1710840. 1380535. 1590793. 1939566. 2944567.]
NEO 2.csv
NEO 2
Stock_CSV/NEO 2.csv
[882051. 573938. 832939. 869148. 867313.]
FTXD.csv
FTXD
Stock_CSV/FTXD.csv
[ 814.  230. 2166. 1963. 1772.]
QFIN 2.csv
QFIN 2
Stock_CSV/QFIN 2.csv
[426171. 437955. 670715. 258124. 942829.]
VUZI.csv
VUZI
Stock_CSV/VUZI.csv
[271926. 200599. 244962. 965651. 819395.]
PDEV.csv
PDEV
Stock_CSV/PDEV.csv
[455.   1.   0.   0.   1.]
PFIN 2.csv
PFIN 2
Stock_CSV/PFIN 2.csv
[2449.  175. 1215. 1263. 1721.]
MILN.csv
MILN
Stock_CSV/MILN.csv
[13072. 28680.  9058. 13068. 13760.]
QLYS 2.csv
QLYS 2
Stock_CSV/QLYS 2.csv
[1094229.  601072.  433426.  472230.  604112.]
SQBG.csv
SQBG
Stock_CSV/SQBG.csv
[1112347.  170930.  335283.  220316.  597698.]
PTGX 2.csv
PTGX 2
Stock_CSV/PTGX 2.csv
[119

TBLTW 2.csv
TBLTW 2
Stock_CSV/TBLTW 2.csv
[71602. 32086. 59760.   190. 38863.]
OSIS 2.csv
OSIS 2
Stock_CSV/OSIS 2.csv
[102560.  76703.  93884. 101734.  87586.]
TCBIP 2.csv
TCBIP 2
Stock_CSV/TCBIP 2.csv
[21367. 21438. 14584. 20272. 26568.]
IAC.csv
IAC
Stock_CSV/IAC.csv
[ 656833.  619439.  873003. 1442625. 1376213.]
ISBC.csv
ISBC
Stock_CSV/ISBC.csv
[1710384. 1287147. 1261095. 2112258. 1871067.]
KIRK.csv
KIRK
Stock_CSV/KIRK.csv
[193989. 277695. 165563. 194071. 367522.]
DHIL.csv
DHIL
Stock_CSV/DHIL.csv
[21564. 16060. 12912. 22354. 23333.]
ALRN.csv
ALRN
Stock_CSV/ALRN.csv
[301540. 362885. 338651. 327521. 396289.]
PPSI 2.csv
PPSI 2
Stock_CSV/PPSI 2.csv
[40544. 35454. 25292. 23865.  8771.]
CVBF.csv
CVBF
Stock_CSV/CVBF.csv
[698874. 592486. 477908. 504202. 745051.]
NYMTO 2.csv
NYMTO 2
Stock_CSV/NYMTO 2.csv
[107034. 178388.  82985. 104031.  60516.]
SNCR.csv
SNCR
Stock_CSV/SNCR.csv
[175071. 130883. 125523. 371925. 141078.]
PPC 2.csv
PPC 2
Stock_CSV/PPC 2.csv
[ 703364.  552311. 1232010. 1063996.  

LMST.csv
LMST
Stock_CSV/LMST.csv
[18233.  4464.   729.  2680.  8446.]
SAQNW.csv
SAQNW
Stock_CSV/SAQNW.csv
[1.20e+03 1.40e+03 1.00e+00 7.53e+04 1.50e+01]
CNSL.csv
CNSL
Stock_CSV/CNSL.csv
[318539. 587814. 424661. 389055. 465495.]
PVAC.csv
PVAC
Stock_CSV/PVAC.csv
[1175246. 1949617. 1455010. 1180988. 1520817.]
TLC.csv
TLC
Stock_CSV/TLC.csv
[ 435. 2934. 1707. 5244. 2069.]
MUDSU.csv
MUDSU
Stock_CSV/MUDSU.csv
[0. 0. 0. 0. 0.]
DIS.csv
DIS
Stock_CSV/DIS.csv
[30568561. 24515003. 28509973. 32478192. 32198863.]
MITK.csv
MITK
Stock_CSV/MITK.csv
[448302. 381606. 207752. 275617. 220699.]
PHCF 2.csv
PHCF 2
Stock_CSV/PHCF 2.csv
[1710.    0.  633. 1128.  432.]
ROSE 2.csv
ROSE 2
Stock_CSV/ROSE 2.csv
[3968632. 2835674. 2561819. 1594031. 5823086.]
TLT.csv
TLT
Stock_CSV/TLT.csv
[14260806. 10147077. 13811848.  9434786.  6570840.]
LMPX.csv
LMPX
Stock_CSV/LMPX.csv
[77904. 31283. 24229. 41533. 29973.]
CETXW.csv
CETXW
Stock_CSV/CETXW.csv
[ 6100. 28441.   942. 13852. 96449.]
MNPR.csv
MNPR
Stock_CSV/MNPR.csv
[ 282

BELFA.csv
BELFA
Stock_CSV/BELFA.csv
[5220.  843. 3675.   27.  833.]
DSKE.csv
DSKE
Stock_CSV/DSKE.csv
[134639. 247309. 155047. 145077. 221925.]
SBNY.csv
SBNY
Stock_CSV/SBNY.csv
[530167. 645807. 484564. 356478. 629855.]
ROAD.csv
ROAD
Stock_CSV/ROAD.csv
[129358. 205005. 180814. 144657. 119586.]
RTTR.csv
RTTR
Stock_CSV/RTTR.csv
[15635060.  8949627.  7239246.  2355081.  4405833.]
PBTS 2.csv
PBTS 2
Stock_CSV/PBTS 2.csv
[25465. 37052. 27559. 37069. 33724.]
KTOVW.csv
KTOVW
Stock_CSV/KTOVW.csv
[62815.  4300.  5266.  1988. 46875.]
ARCB.csv
ARCB
Stock_CSV/ARCB.csv
[128234. 236254. 134998. 173294. 176369.]
WSC.csv
WSC
Stock_CSV/WSC.csv
[444616. 763684. 632106. 494237. 649605.]
WINA.csv
WINA
Stock_CSV/WINA.csv
[15983. 26265. 34008. 22722. 29530.]
BIB.csv
BIB
Stock_CSV/BIB.csv
[189863. 302858. 164508. 208566. 300501.]
ELTK.csv
ELTK
Stock_CSV/ELTK.csv
[55146. 17067. 26302. 10819. 47255.]
ROAD 2.csv
ROAD 2
Stock_CSV/ROAD 2.csv
[474398. 333023. 284411. 331929. 268709.]
PNNTG.csv
PNNTG
Stock_CSV/PNNTG.c

PTON.csv
PTON
Stock_CSV/PTON.csv
[5549147. 3959334. 6167123. 7596606. 7756101.]
ABT.csv
ABT
Stock_CSV/ABT.csv
[ 8337903. 10500949.  9350991. 10900888. 13032018.]
MTC.csv
MTC
Stock_CSV/MTC.csv
[ 8086. 13390. 19840.  5384.  3361.]
MRTX.csv
MRTX
Stock_CSV/MRTX.csv
[ 897589.  840656.  382109. 1057954.  557662.]
FFIC.csv
FFIC
Stock_CSV/FFIC.csv
[ 77095.  85093. 111488.  83963.  90072.]
SONM 2.csv
SONM 2
Stock_CSV/SONM 2.csv
[133150. 124326. 221107.  79361. 213055.]
RELL.csv
RELL
Stock_CSV/RELL.csv
[ 6075.  7982. 47354. 11861. 24368.]
OFIX.csv
OFIX
Stock_CSV/OFIX.csv
[124973.  93133. 125753. 128222.  82797.]
TTPH.csv
TTPH
Stock_CSV/TTPH.csv
[123150.  44021.  77427. 168903.  66074.]
HALL.csv
HALL
Stock_CSV/HALL.csv
[245118. 178172. 129390. 171165. 151970.]
SKYS 2.csv
SKYS 2
Stock_CSV/SKYS 2.csv
[10891.  3004.   625.  3661.  1844.]
THWWW 2.csv
THWWW 2
Stock_CSV/THWWW 2.csv
[7.50000e+01 1.55212e+05 1.00000e+01 3.40020e+04 3.45310e+04]
PACB.csv
PACB
Stock_CSV/PACB.csv
[1887237. 1878199. 2022392.

METC.csv
METC
Stock_CSV/METC.csv
[79245. 71751. 43278. 21047. 19109.]
RUN 2.csv
RUN 2
Stock_CSV/RUN 2.csv
[2662529. 2260991. 3078574. 2226713. 2264709.]
AAME.csv
AAME
Stock_CSV/AAME.csv
[30481.    94.  2775.  7644.   885.]
MUDSU 2.csv
MUDSU 2
Stock_CSV/MUDSU 2.csv
[   0.    0. 1000.    0.    0.]
TAST 2.csv
TAST 2
Stock_CSV/TAST 2.csv
[1097673. 1202397.  842897.  538753. 1182666.]
CBSHP.csv
CBSHP
Stock_CSV/CBSHP.csv
[1129. 3970. 2166. 4589. 2440.]
HHHHW.csv
HHHHW
Stock_CSV/HHHHW.csv
[16875.   600.   100.   100.   200.]
TCCO 2.csv
TCCO 2
Stock_CSV/TCCO 2.csv
[ 4770.  1893.  3981. 13352. 50311.]
ORSNR 2.csv
ORSNR 2
Stock_CSV/ORSNR 2.csv
[ 1400.   102.   700. 16730.   200.]
AXAS.csv
AXAS
Stock_CSV/AXAS.csv
[1.43923947e+08 1.13123342e+08 7.00747400e+06 5.69460000e+06
 6.49328500e+06]
WATT.csv
WATT
Stock_CSV/WATT.csv
[2.15342900e+06 6.82857700e+06 1.43869600e+07 1.23721955e+08
 5.08689000e+05]
MRTN.csv
MRTN
Stock_CSV/MRTN.csv
[194286. 266170. 204791. 214508. 256331.]
STX 2.csv
STX 2
Stock_CS

REED 2.csv
REED 2
Stock_CSV/REED 2.csv
[375871. 513448. 113927.  86307. 114172.]
EBTC.csv
EBTC
Stock_CSV/EBTC.csv
[ 6687.  9759. 13820. 20459.  5838.]
EIGI.csv
EIGI
Stock_CSV/EIGI.csv
[ 413400.  408210. 1226184. 1357722.  945612.]
ITRN.csv
ITRN
Stock_CSV/ITRN.csv
[34254. 99253. 42901. 28931. 62880.]
AGTC.csv
AGTC
Stock_CSV/AGTC.csv
[101598. 179934. 119044.  99784. 136630.]
SEED 2.csv
SEED 2
Stock_CSV/SEED 2.csv
[82838. 14310. 26942. 22703.  5172.]
PBPB.csv
PBPB
Stock_CSV/PBPB.csv
[176284. 123348. 136395. 116055. 147404.]
SIVB 2.csv
SIVB 2
Stock_CSV/SIVB 2.csv
[795775. 372730. 592641. 687336. 591552.]
THCAU 2.csv
THCAU 2
Stock_CSV/THCAU 2.csv
[3. 3. 0. 0. 1.]
SUNS.csv
SUNS
Stock_CSV/SUNS.csv
[52535. 28614. 49147. 57699. 71839.]
GOOGL.csv
GOOGL
Stock_CSV/GOOGL.csv
[2701423. 2016713. 3080955. 3165991. 2568694.]
TCOM 2.csv
TCOM 2
Stock_CSV/TCOM 2.csv
[ 7007574.  8439352.  5343161.  8908748. 10152296.]
NGHC 2.csv
NGHC 2
Stock_CSV/NGHC 2.csv
[551614. 513543. 685348. 486720. 477348.]
NTRP.csv

UGLD.csv
UGLD
Stock_CSV/UGLD.csv
[233677. 107965. 194823. 253772. 118921.]
AMCA.csv
AMCA
Stock_CSV/AMCA.csv
[   0.    0.    8.   12. 2502.]
ACMR.csv
ACMR
Stock_CSV/ACMR.csv
[332056. 288639. 298980. 343695. 211478.]
LOGC.csv
LOGC
Stock_CSV/LOGC.csv
[41911. 56088. 55224. 52495. 37562.]
SUSL 2.csv
SUSL 2
Stock_CSV/SUSL 2.csv
[189951.  21013.  18251.  18887.  15517.]
PFIS.csv
PFIS
Stock_CSV/PFIS.csv
[ 9781. 10408. 19172.  5239.  5410.]
ANDAU.csv
ANDAU
Stock_CSV/ANDAU.csv
[  0.   0. 600.   4.   0.]
IBTB.csv
IBTB
Stock_CSV/IBTB.csv
[  49. 1100.    3. 1003.   35.]
MTBCP.csv
MTBCP
Stock_CSV/MTBCP.csv
[ 60874. 219940.  70666.  19743.  18910.]
RBZ 2.csv
RBZ 2
Stock_CSV/RBZ 2.csv
[111135. 166997. 133040. 129034. 190229.]
SONO 2.csv
SONO 2
Stock_CSV/SONO 2.csv
[1264561. 1284326. 1318636. 1007789.  829842.]
LSTR.csv
LSTR
Stock_CSV/LSTR.csv
[285897. 715013. 287177. 262364. 355001.]
BCPC.csv
BCPC
Stock_CSV/BCPC.csv
[121916. 120038. 158424. 108332.  96944.]
HYACW.csv
HYACW
Stock_CSV/HYACW.csv
[351333.

PETZ.csv
PETZ
Stock_CSV/PETZ.csv
[ 2138. 11538.  3530.  7949.  5974.]
NODK.csv
NODK
Stock_CSV/NODK.csv
[27672. 30282. 21551. 35131. 33773.]
SMRT 2.csv
SMRT 2
Stock_CSV/SMRT 2.csv
[ 67467.  67546. 206540. 382567. 285583.]
SPRO.csv
SPRO
Stock_CSV/SPRO.csv
[ 97847. 127744.  48005.  65367. 114574.]
QTEC 2.csv
QTEC 2
Stock_CSV/QTEC 2.csv
[221558. 452048. 312439. 224684. 127026.]
APWC.csv
APWC
Stock_CSV/APWC.csv
[5025. 2220. 2087. 4341.  454.]
APTX.csv
APTX
Stock_CSV/APTX.csv
[117807. 184866. 413088.  52516. 191600.]
PUI 2.csv
PUI 2
Stock_CSV/PUI 2.csv
[46802.  9866. 20904. 19790. 18808.]
BNTCW.csv
BNTCW
Stock_CSV/BNTCW.csv
[   0. 3350.  800.  200.  101.]
NMRD.csv
NMRD
Stock_CSV/NMRD.csv
[91376.  5684.  2985. 15441.  3227.]
FPXE.csv
FPXE
Stock_CSV/FPXE.csv
[1.0000e+00 0.0000e+00 7.1000e+02 3.5500e+02 1.4842e+04]
IDXG.csv
IDXG
Stock_CSV/IDXG.csv
[211579. 166860. 158913.  22386.  19854.]
HNRG.csv
HNRG
Stock_CSV/HNRG.csv
[369136. 318037. 232773. 269540. 310826.]
SHOO 2.csv
SHOO 2
Stock_CSV/SHOO

PWOD 2.csv
PWOD 2
Stock_CSV/PWOD 2.csv
[11103. 18590. 19912. 18350. 20501.]
AIA.csv
AIA
Stock_CSV/AIA.csv
[ 38752. 131979.  48699.  79823.  57397.]
IRBT.csv
IRBT
Stock_CSV/IRBT.csv
[1642919.  743969. 1280220.  670755.  740744.]
EXTR.csv
EXTR
Stock_CSV/EXTR.csv
[ 637264.  945428.  756477.  726415. 1035809.]
AMRN.csv
AMRN
Stock_CSV/AMRN.csv
[20686719.  8528222.  7018115.  9158718. 12880015.]
SSPK 2.csv
SSPK 2
Stock_CSV/SSPK 2.csv
[25529.  2845.   964. 23678. 11609.]
IRCP.csv
IRCP
Stock_CSV/IRCP.csv
[  59. 2093. 2801. 6907. 1949.]
WVVIP.csv
WVVIP
Stock_CSV/WVVIP.csv
[573.   0.   0. 250.   0.]
MLVF.csv
MLVF
Stock_CSV/MLVF.csv
[ 7870. 13740.  7737. 11187.  9589.]
NVEE 2.csv
NVEE 2
Stock_CSV/NVEE 2.csv
[ 95809. 102338. 103470. 190920. 179758.]
OXSQ 2.csv
OXSQ 2
Stock_CSV/OXSQ 2.csv
[1012861.  661313.  572387.  311264.  555957.]
SAMA.csv
SAMA
Stock_CSV/SAMA.csv
[105237.      0.   1591.      0.      0.]
THFF.csv
THFF
Stock_CSV/THFF.csv
[39120. 56213. 37136. 48996. 51913.]
ROLL 2.csv
ROLL 2
Sto

RDNT 2.csv
RDNT 2
Stock_CSV/RDNT 2.csv
[835650. 752958. 872968. 879522. 359142.]
CERC.csv
CERC
Stock_CSV/CERC.csv
[113673. 107915.  94603.  93232.  91366.]
PFHD 2.csv
PFHD 2
Stock_CSV/PFHD 2.csv
[113366.  60130.  20992.  37257.  47892.]
MYSZ 2.csv
MYSZ 2
Stock_CSV/MYSZ 2.csv
[27047.  6070. 13696. 13528. 15152.]
GROW.csv
GROW
Stock_CSV/GROW.csv
[ 66793. 353082.  69929.  31447.  85002.]
EMCB.csv
EMCB
Stock_CSV/EMCB.csv
[ 419. 1217. 2057. 3860. 2828.]
RRGB.csv
RRGB
Stock_CSV/RRGB.csv
[736771. 409419. 559877. 452228. 619892.]
BVXV.csv
BVXV
Stock_CSV/BVXV.csv
[11549.  9048. 11886. 41749. 45570.]
FFBW.csv
FFBW
Stock_CSV/FFBW.csv
[ 352. 2470. 1401. 3013.  206.]
SMTX.csv
SMTX
Stock_CSV/SMTX.csv
[70059. 56422. 60646. 68789. 87999.]
SBFG 2.csv
SBFG 2
Stock_CSV/SBFG 2.csv
[16869.  3193.  5296.  6832.  4175.]
ON.csv
ON
Stock_CSV/ON.csv
[ 5266537.  5998738. 10389560.  6079055.  5184681.]
INSM.csv
INSM
Stock_CSV/INSM.csv
[ 814144.  891252.  957031.  876911. 1261905.]
DGICA.csv
DGICA
Stock_CSV/DGICA.

PERI.csv
PERI
Stock_CSV/PERI.csv
[200248. 139171. 248083. 196392. 162152.]
SLGL.csv
SLGL
Stock_CSV/SLGL.csv
[ 7135. 10821. 13536.  7863.  4039.]
TRMB.csv
TRMB
Stock_CSV/TRMB.csv
[ 825993.  949976.  561944.  766380. 1154116.]
USWS.csv
USWS
Stock_CSV/USWS.csv
[1752093. 1926479. 1068215. 2623935. 1335139.]
EBSB.csv
EBSB
Stock_CSV/EBSB.csv
[132640. 270779. 150921.  96631. 129325.]
CARE.csv
CARE
Stock_CSV/CARE.csv
[ 20204.  65946.  45508. 117573.  47948.]
RMCF 2.csv
RMCF 2
Stock_CSV/RMCF 2.csv
[33418. 18611. 44316. 78930. 20915.]
QCOM.csv
QCOM
Stock_CSV/QCOM.csv
[6037799. 7673845. 7367881. 9273758. 7217667.]
JMPNL.csv
JMPNL
Stock_CSV/JMPNL.csv
[9374. 8475. 4115. 2600. 3160.]
OPHC 2.csv
OPHC 2
Stock_CSV/OPHC 2.csv
[  0.   1. 251.  67. 152.]
NRC 2.csv
NRC 2
Stock_CSV/NRC 2.csv
[41524. 36449. 63582. 48793. 69735.]
BNDX.csv
BNDX
Stock_CSV/BNDX.csv
[1570764. 1517203. 1224563. 1511363. 1950980.]
CASA.csv
CASA
Stock_CSV/CASA.csv
[201727. 343687. 255941. 187830. 313157.]
TGTX.csv
TGTX
Stock_CSV/TGT

XENT.csv
XENT
Stock_CSV/XENT.csv
[243114. 662417. 241397. 395513. 670575.]
MTEM 2.csv
MTEM 2
Stock_CSV/MTEM 2.csv
[180068. 233197. 157649. 202106. 173999.]
DRIO.csv
DRIO
Stock_CSV/DRIO.csv
[213557.  54447.  25173.   9530.  17642.]
PAHC.csv
PAHC
Stock_CSV/PAHC.csv
[132989. 125088. 236172. 146964. 130147.]
IEUS.csv
IEUS
Stock_CSV/IEUS.csv
[12621. 18969.  7888.  3619. 16620.]
CLBS.csv
CLBS
Stock_CSV/CLBS.csv
[ 73968. 849053.  38538.   5467.   6016.]
FTHI.csv
FTHI
Stock_CSV/FTHI.csv
[23611.  5614. 13666. 14202. 18320.]
SFST.csv
SFST
Stock_CSV/SFST.csv
[10897. 14817. 14313. 48199. 20701.]
WTREP.csv
WTREP
Stock_CSV/WTREP.csv
[200.   0.   0.   0.  50.]
STML.csv
STML
Stock_CSV/STML.csv
[1179208.  601310.  586962.  593626.  471805.]
CPRX.csv
CPRX
Stock_CSV/CPRX.csv
[1573670. 2394081. 1222725. 2126826. 2762613.]
SLGG 2.csv
SLGG 2
Stock_CSV/SLGG 2.csv
[ 580453.  371158.  662708. 1590442.  278628.]
PAYX 2.csv
PAYX 2
Stock_CSV/PAYX 2.csv
[2877355. 3171849. 4136384. 3475714. 6192903.]
PODD 2.csv
POD

CTHR.csv
CTHR
Stock_CSV/CTHR.csv
[268899. 183145.  22544. 116491.  70690.]
JMPNZ.csv
JMPNZ
Stock_CSV/JMPNZ.csv
[3251. 1335. 2085. 3838.    0.]
DJCO.csv
DJCO
Stock_CSV/DJCO.csv
[ 873. 1935. 3447.  726. 1555.]
MARA.csv
MARA
Stock_CSV/MARA.csv
[ 658587. 3280333.  109827.  342894.  175536.]
BBQ.csv
BBQ
Stock_CSV/BBQ.csv
[11614. 17279. 15363.  7873. 21925.]
VVUS.csv
VVUS
Stock_CSV/VVUS.csv
[345931. 280019. 305027. 327554. 490781.]
KBSF.csv
KBSF
Stock_CSV/KBSF.csv
[184133.  33489.  56226. 680654.   9971.]
IDRA.csv
IDRA
Stock_CSV/IDRA.csv
[167833. 256009. 271839. 354430. 564299.]
POLA 2.csv
POLA 2
Stock_CSV/POLA 2.csv
[ 76279. 140238.  48208.  33551.  92548.]
TRMT.csv
TRMT
Stock_CSV/TRMT.csv
[157768.  74085.  58525.  66144.  38258.]
PPHI.csv
PPHI
Stock_CSV/PPHI.csv
[  14.    0.  200. 2264.    0.]
NEBUU.csv
NEBUU
Stock_CSV/NEBUU.csv
[4186.  600. 1020.    0.    0.]
HYZD.csv
HYZD
Stock_CSV/HYZD.csv
[18373. 54690. 31706. 36187. 67263.]
OPRX.csv
OPRX
Stock_CSV/OPRX.csv
[ 83422. 109837.  38089.  50

SWKH 2.csv
SWKH 2
Stock_CSV/SWKH 2.csv
[5528. 2140. 2192. 2218. 1001.]
PSCH.csv
PSCH
Stock_CSV/PSCH.csv
[33377. 11119. 15672. 21169. 21981.]
CIIC.csv
CIIC
Stock_CSV/CIIC.csv
[2120. 1400.    0. 2321. 1109.]
PDLB 2.csv
PDLB 2
Stock_CSV/PDLB 2.csv
[12471. 14149. 30348. 15764. 18603.]
PTEN.csv
PTEN
Stock_CSV/PTEN.csv
[ 8784330. 12493394.  6742785.  6512830.  5995158.]
SQLV 2.csv
SQLV 2
Stock_CSV/SQLV 2.csv
[ 3262.   407. 22063.    68.   771.]
CPTAL.csv
CPTAL
Stock_CSV/CPTAL.csv
[4425. 2540. 1317. 1136.   11.]
ZJZZT.csv
ZJZZT
Stock_CSV/ZJZZT.csv
[  150.   150.   150.   300. 82650.]
FSTR.csv
FSTR
Stock_CSV/FSTR.csv
[42397. 34729. 60778. 34692. 40450.]
HON.csv
HON
Stock_CSV/HON.csv
[3924936. 5600123. 7158629. 5797920. 8197570.]
DBVT.csv
DBVT
Stock_CSV/DBVT.csv
[117607. 128822. 168590.  74191. 206113.]
GENY.csv
GENY
Stock_CSV/GENY.csv
[ 190. 1709.  237. 2080.  622.]
BSJP.csv
BSJP
Stock_CSV/BSJP.csv
[178116.  51348.  26387.  26629.  34271.]
HOFT.csv
HOFT
Stock_CSV/HOFT.csv
[ 79738. 104352.  595

OXLCM.csv
OXLCM
Stock_CSV/OXLCM.csv
[ 6455.  9955. 14960. 19499. 12771.]
OMP 2.csv
OMP 2
Stock_CSV/OMP 2.csv
[402128. 261199. 284976. 304232. 332054.]
PMOM 2.csv
PMOM 2
Stock_CSV/PMOM 2.csv
[0. 4. 3. 2. 4.]
TAOP.csv
TAOP
Stock_CSV/TAOP.csv
[ 68795. 106084.  69182.  48408.  28509.]
MBUU.csv
MBUU
Stock_CSV/MBUU.csv
[243605. 222033. 137183. 193769. 168327.]
CIGI.csv
CIGI
Stock_CSV/CIGI.csv
[ 75894.  66058.  97944.  55884. 117650.]
SVMK.csv
SVMK
Stock_CSV/SVMK.csv
[368226. 610217. 549043. 770520. 504859.]
BSJQ.csv
BSJQ
Stock_CSV/BSJQ.csv
[39361.  9466. 39166.  4740. 18031.]
BCOV.csv
BCOV
Stock_CSV/BCOV.csv
[ 88168. 170620. 143349. 126449. 112213.]
SSRM.csv
SSRM
Stock_CSV/SSRM.csv
[1640494. 2236507. 1832448. 1771868. 1587137.]
NEOG.csv
NEOG
Stock_CSV/NEOG.csv
[166424. 196648. 128107. 144327. 195551.]
AIQ.csv
AIQ
Stock_CSV/AIQ.csv
[15752.  6986. 35635. 11695. 38699.]
LMNX.csv
LMNX
Stock_CSV/LMNX.csv
[404778. 451668. 569589. 488524. 450318.]
MNOV.csv
MNOV
Stock_CSV/MNOV.csv
[149416. 152169. 1

BMY.csv
BMY
Stock_CSV/BMY.csv
[14494812. 21599571. 20918294. 16481668. 21234344.]
RBB 2.csv
RBB 2
Stock_CSV/RBB 2.csv
[72228. 90038. 69183. 79360. 52879.]
BPYPN.csv
BPYPN
Stock_CSV/BPYPN.csv
[16811. 13101. 12039. 21696. 12404.]
PRTA 2.csv
PRTA 2
Stock_CSV/PRTA 2.csv
[237636. 227996. 283547. 264984. 212565.]
CDMOP.csv
CDMOP
Stock_CSV/CDMOP.csv
[4860. 1557. 3868. 9706. 8357.]
EYESW.csv
EYESW
Stock_CSV/EYESW.csv
[ 1322.  3260. 13728. 17882. 21250.]
WYNN.csv
WYNN
Stock_CSV/WYNN.csv
[ 4962484. 10329589.  3944929.  5283887.  5939564.]
LILA.csv
LILA
Stock_CSV/LILA.csv
[262988. 440710. 324343. 369977. 367687.]
SNOA 2.csv
SNOA 2
Stock_CSV/SNOA 2.csv
[ 2897.  2661.  5952. 11540. 22426.]
SYRS.csv
SYRS
Stock_CSV/SYRS.csv
[240696. 308618. 387898. 352205. 388103.]
NWSA 2.csv
NWSA 2
Stock_CSV/NWSA 2.csv
[5212174. 3740339. 5625475. 3163939. 3341434.]
CHUY.csv
CHUY
Stock_CSV/CHUY.csv
[132076. 242659. 219794. 170869. 231205.]
SEAC.csv
SEAC
Stock_CSV/SEAC.csv
[371803. 323183. 751082. 468565. 528642.]
CXS

NICK.csv
NICK
Stock_CSV/NICK.csv
[ 288. 1788.  508.  893. 1156.]
OPI.csv
OPI
Stock_CSV/OPI.csv
[213522. 197898. 223697. 274394. 229743.]
BANR.csv
BANR
Stock_CSV/BANR.csv
[127177. 169234. 147179. 171044. 144704.]
ASNA.csv
ASNA
Stock_CSV/ASNA.csv
[542852. 286253. 253999. 579964. 227239.]
KALV.csv
KALV
Stock_CSV/KALV.csv
[ 66762.  69803.  76941.  82391. 111520.]
PHAT.csv
PHAT
Stock_CSV/PHAT.csv
[15513. 50502. 35342. 46873. 27620.]
OPRA 2.csv
OPRA 2
Stock_CSV/OPRA 2.csv
[581843. 300148. 248567. 198635. 157530.]
FYX.csv
FYX
Stock_CSV/FYX.csv
[ 42211. 109655. 162062. 161128.  32021.]
SCON.csv
SCON
Stock_CSV/SCON.csv
[1104791. 1045855.  953053. 1046065. 4032720.]
PRIM 2.csv
PRIM 2
Stock_CSV/PRIM 2.csv
[165136. 234351. 228236. 396479. 259972.]
FARO.csv
FARO
Stock_CSV/FARO.csv
[ 74865.  91485.  91375. 104481. 104932.]
SINA 2.csv
SINA 2
Stock_CSV/SINA 2.csv
[ 594583.  544328. 1058264.  767643. 1019860.]
MYL 2.csv
MYL 2
Stock_CSV/MYL 2.csv
[9791985. 5861266. 8622662. 9635466. 8137135.]
XENE.csv
X