In [5]:
#Install the dependencies
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib. pyplot as plt

In [6]:
## stock list to iterate through
stock_list = ['AAPL','ABBV','ABT','ACN','AGN','AIG','ALL','AMGN','AMZN','BA','BAC','BIIB','BK','BKNG',
              'BMY','BRK.B','C','CAT','CHTR','CMCSA','COF','COST','CSCO','CVS','DD','DHR','DIS',
                'DOW','DUK','EXC','F','FB','FDX','GD','GILD','GM','GOOG','GOOGL','GS','HON','IBM',
                'INTC','JNJ','JPM','KMI','KO','LLY','LMT','LOW','MCD','MDLZ','MDT','MET','MMM','MRK',
                'MS','MSFT','NEE','NFLX','NVDA','ORCL','OXY','PEP','PFE','PM','PYPL','QCOM','RTN','SBUX',
                'SO','SPG','T','TGT','TMO','UNH','UNP','UPS','USB','UTX','VZ','WBA','WFC','WMT','XOM']

In [7]:
days = ['M', 'T', 'W', 'Th', 'F']
plt.clf()
for stock in stock_list:
    print(stock)
    df = pd.read_csv("moving average tests/stock_csv_avg_test/" + stock + '.csv') 
    df= df[['5. volume']]
    volumes = df.iloc[0:5].values
    result = volumes.ravel() 
    print(result)
    
    plt.bar(days, result, color = 'violet')
    plt.title(stock + ': Average Volume per Day in Past Month')
    plt.xlabel('Days')
    plt.ylabel('Volume')
    #plt.show()
    
    
    # adding to plots_test folder
    plt.savefig('SP100_volume_charts/' + stock + '.png')
    plt.clf()
    # clears plot so that plots do not overlap on one plot
    #plt.clf()

AAPL
[51054153. 63140169. 75900510. 71882773. 84188208.]
ABBV
[12289695. 15978894. 20010683. 18364705. 19201245.]
ABT
[ 8337903. 10500949.  9350991. 10900888. 13032018.]
ACN
[3802436. 5194360. 4795480. 4684046. 6173727.]
AGN
[3421364. 5473084. 5966581. 3690655. 4942147.]
AIG
[ 9469393. 11282618. 14362424. 11409210.  9604478.]
ALL
[2662532. 3563458. 3539566. 3197448. 3181080.]
AMGN
[4119780. 5162547. 5301004. 5288247. 4396603.]
AMZN
[5387897. 6235118. 6479073. 7147080. 7808489.]
BA
[47729982. 63172068. 77314766. 42870185. 45885390.]
BAC
[9.14156170e+07 1.16044233e+08 1.46780467e+08 1.47475263e+08
 1.81381030e+08]
BIIB
[1653113. 2270494. 2678911. 3464065. 2695449.]
BK
[5764473. 8440925. 9866627. 9411081. 8554646.]
BKNG
[701507. 616548. 998892. 853989. 859891.]
BMY
[14494812. 21599571. 20918294. 16481668. 21234344.]
BRK.B
[10258794. 14126526. 13842256. 14063092. 16499448.]
C
[25471653. 31526377. 38185069. 34051238. 32982636.]
CAT
[5745007. 6059607. 6577059. 7409740. 6734663.]
CHTR
[190994

<Figure size 432x288 with 0 Axes>