In [134]:
#Install the dependencies
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib. pyplot as plt
import os

In [144]:
arr = []
with open("NASDAQ_ex.txt", "r") as filestream:
    for line in filestream:
        currentline = line.split(',')
        arr.append(currentline)
    stock_list = np.array(arr[0])


days = ['M', 'T', 'W', 'Th', 'F']
plt.clf()
for stock in stock_list:
    try:        
        print(stock)
        df = pd.read_csv("Stock_CSV/" + stock + '.csv') 
        df= df[['5. volume']]
        volumes = df.iloc[0:5].values
        result = volumes.ravel() 
        print(result)

        plt.bar(days, result, color = 'violet')
        plt.title('Average Volume per Day in Past Month')
        plt.xlabel('Days')
        plt.ylabel('Volume')
    #plt.show()

    
    
    # adding to plots_test folder
        plt.savefig('VOLUME_CHARTS/NASDAQ_volume_charts/' + stock + '.png')
        plt.clf()
    except pd.errors.EmptyDataError:
        print("Found empty file : {file}".format(file=file))
    # clears plot so that plots do not overlap on one plot
    #plt.clf()

AACG
[ 7119.  3908. 16506. 10304.  3009.]
AAL
[66854629. 54598512. 76320112. 49882258. 58984927.]
AAME
[30481.    94.  2775.  7644.   885.]
AAOI
[783352. 495949. 566763. 754950. 673295.]
AAPL
[31274973. 31203582. 29264342. 45247893. 32503750.]
AAWW
[493679. 612064. 743780. 800571. 546205.]
AAXJ
[ 652515. 1039207.  556157.  663091.  940476.]
AAXN
[ 815924.  502777.  341503.  849611. 1562435.]
ABCB
[600119. 363773. 241140. 360081. 340851.]
ABIO
[10696.  8799. 23212. 20914. 25770.]
ABMD
[600499. 443853. 328531. 391060. 342852.]
ABTX
[53787. 92886. 78512. 87309. 76976.]
ABUS
[331291. 489259. 199163. 498268. 756737.]
ACAD
[1068117. 1014156. 1206106. 1046230. 1949572.]
ACAMU
[  5.  99. 800. 291. 100.]
ACAMW
[3.70000e+01 1.00000e+00 2.68670e+04 5.00000e+03 1.66866e+05]
ACBI
[63555. 60836. 32105. 34644. 30323.]
ACER
[15643. 23626. 44740. 20793. 49861.]
ACGL
[1955796. 1509750. 1992008. 1998017. 1890332.]
ACGLP
[37819. 37977. 27734. 54025. 27120.]
ACHC
[808753. 575068. 494045. 771632. 554425.]
A

FileNotFoundError: [Errno 2] File Stock_CSV/AMTD.csv does not exist: 'Stock_CSV/AMTD.csv'

In [141]:
#days = ['M', 'T', 'W', 'Th', 'F']
#numbers = [1,2,3,4,5]

#plt.bar(days, numbers)
#plt.title('Average Volume per Day in Past Month for '+ stock)
#plt.xlabel('Days')
#plt.ylabel('Volume')
#plt.show()


In [ ]:
import glob

path = "Stock_CSV/*.csv"
for fname in glob.glob(path):
    third_to_fifth_chars = fname[10:len(fname)]
    print(third_to_fifth_chars)
    third_to_fifth_chars = third_to_fifth_chars[:len(third_to_fifth_chars)-3]
    print(third_to_fifth_chars)
    print(fname)
    '''
    df = pd.read_csv(fname) 
    df= df[['5. volume']]
    volumes = df.iloc[0:5].values
    result = volumes.ravel() 
    print(result)
    
    plt.bar(days, result, color = 'violet')
    plt.title(third_to_fifth_chars + ': Average Volume per Day in Past Month')
    plt.xlabel('Days')
    plt.ylabel('Volume')
    #plt.show()

    
    
    # adding to plots_test folder
    plt.savefig('VOLUME_CHARTS/Test/' + third_to_fifth_chars + '.png')
    plt.clf()
    '''
    

ANTE.csv
ANTE.
Stock_CSV/ANTE.csv
CSCO.csv
CSCO.
Stock_CSV/CSCO.csv
LACQW.csv
LACQW.
Stock_CSV/LACQW.csv
TOTA 2.csv
TOTA 2.
Stock_CSV/TOTA 2.csv
HLNE.csv
HLNE.
Stock_CSV/HLNE.csv
OCSI 2.csv
OCSI 2.
Stock_CSV/OCSI 2.csv
PSM.csv
PSM.
Stock_CSV/PSM.csv
SBGI.csv
SBGI.
Stock_CSV/SBGI.csv
UFCS.csv
UFCS.
Stock_CSV/UFCS.csv
GFED.csv
GFED.
Stock_CSV/GFED.csv
PAVMZ 2.csv
PAVMZ 2.
Stock_CSV/PAVMZ 2.csv
AIRT.csv
AIRT.
Stock_CSV/AIRT.csv
SUSC 2.csv
SUSC 2.
Stock_CSV/SUSC 2.csv
SMSI 2.csv
SMSI 2.
Stock_CSV/SMSI 2.csv
NBL 2.csv
NBL 2.
Stock_CSV/NBL 2.csv
ISSC.csv
ISSC.
Stock_CSV/ISSC.csv
KNDI.csv
KNDI.
Stock_CSV/KNDI.csv
THCBW 2.csv
THCBW 2.
Stock_CSV/THCBW 2.csv
TRNS.csv
TRNS.
Stock_CSV/TRNS.csv
TLND 2.csv
TLND 2.
Stock_CSV/TLND 2.csv
TRIP 2.csv
TRIP 2.
Stock_CSV/TRIP 2.csv
UAL.csv
UAL.
Stock_CSV/UAL.csv
TROW.csv
TROW.
Stock_CSV/TROW.csv
ISRG.csv
ISRG.
Stock_CSV/ISRG.csv
TPCO 2.csv
TPCO 2.
Stock_CSV/TPCO 2.csv
RDVY.csv
RDVY.
Stock_CSV/RDVY.csv
TELA.csv
TELA.
Stock_CSV/TELA.csv
RVSB 2.csv
RVSB 2.
Sto