In [61]:
#Install the dependencies
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib. pyplot as plt

In [62]:
arr = []
with open("NASDAQ2.txt", "r") as filestream:
    for line in filestream:
        currentline = line.split(',')
        arr.append(currentline)
    stock_list = np.array(arr[0])

In [63]:
stock_list

array(['SAFM', 'SAFT', 'SAGE', 'SAIA', 'SAL', 'SALM', 'SAMA', 'SAMAU',
       'SAMAW', 'SAMG', 'SANM', 'SANW', 'SAQN', 'SAQNU', 'SAQNW', 'SASR',
       'SATS', 'SAVA', 'SBAC', 'SBBP', 'SBBX', 'SBCF', 'SBFG', 'SBGI',
       'SBLK', 'SBLKZ', 'SBNY', 'SBPH', 'SBRA', 'SBSI', 'SBT', 'SBUX',
       'SCHL', 'SCHN', 'SCKT', 'SCON', 'SCOR', 'SCPH', 'SCPL', 'SCSC',
       'SCVL', 'SCWX', 'SCYX', 'SCZ', 'SDC', 'SDG', 'SDGR', 'SDVY',
       'SEAC', 'SECO', 'SEDG', 'SEED', 'SEEL', 'SEIC', 'SELB', 'SELF',
       'SENEA', 'SENEB', 'SES', 'SESN', 'SFBC', 'SFBS', 'SFET', 'SFIX',
       'SFM', 'SFNC', 'SFST', 'SG', 'SGA', 'SGBX', 'SGC', 'SGEN', 'SGH',
       'SGLB', 'SGLBW', 'SGMA', 'SGMO', 'SGMS', 'SGOC', 'SGRP', 'SGRY',
       'SHBI', 'SHEN', 'SHIP', 'SHIPW', 'SHIPZ', 'SHLO', 'SHOO', 'SHSP',
       'SHV', 'SHY', 'SIBN', 'SIC', 'SIEB', 'SIEN', 'SIFY', 'SIGA',
       'SIGI', 'SILC', 'SILK', 'SIMO', 'SINA', 'SINO', 'SINT', 'SIRI',
       'SITM', 'SIVB', 'SIVBP', 'SKOR', 'SKYS', 'SKYW', 'SKYY', 'SLAB',
  

In [70]:
days = ['M', 'T', 'W', 'Th', 'F']
plt.clf()
for stock in stock_list:
    print(stock)
    df = pd.read_csv("Stock_CSV/" + stock + '.csv') 
    df= df[['5. volume']]
    volumes = df.iloc[0:5].values
    result = volumes.ravel() 
    print(result)
    
    plt.bar(days, result, color = 'violet')
    plt.title(stock + ': Average Volume per Day in Past Month')
    plt.xlabel('Days')
    plt.ylabel('Volume')
    #plt.show()
    
    
    # adding to plots_test folder
    plt.savefig('NASDAQ_volume_charts/' + stock + '.png')
    plt.clf()
    # clears plot so that plots do not overlap on one plot
    #plt.clf()

SAFM
[367655. 397143. 285895. 246233. 446529.]
SAFT
[65275. 65105. 42797. 45840. 43489.]
SAGE
[1252983.  949651. 1081873. 1928477. 2748540.]
SAIA
[252799. 417912. 261037. 218416. 147293.]
SAL
[2418. 2679. 1669. 3481.  233.]
SALM
[40800. 78273. 64081. 48621. 39773.]
SAMA
[105237.      0.   1591.      0.      0.]
SAMAU
[0. 0. 0. 0. 0.]
SAMAW
[1.81548e+05 5.00000e+05 2.00000e+02 3.50000e+02 2.00000e+02]
SAMG
[ 9365. 10553. 19269.  8917.  4070.]
SANM
[433895. 486384. 410953. 573282. 520380.]
SANW
[ 6551.  2970. 19309.  3297. 23943.]
SAQN
[ 5102.  2250.  8389.     0. 21139.]
SAQNU
[3.500e+03 2.849e+03 1.000e+03 0.000e+00 1.000e+00]
SAQNW
[1.20e+03 1.40e+03 1.00e+00 7.53e+04 1.50e+01]
SASR
[174402. 278821. 168400. 189883. 159536.]
SATS
[367484. 472285. 746344. 662199. 720806.]
SAVA
[1478937. 5435731.  476965.  492797.  763780.]
SBAC
[610940. 637268. 608219. 555802. 585812.]
SBBP
[178870. 177129. 216359. 268815. 455042.]
SBBX
[ 6445. 16007.  9174. 17881. 17140.]
SBCF
[165794. 173519. 220032. 

SORL
[74335. 46265. 45381. 17240. 37853.]
SOXX
[ 930733.  977694. 1113839. 1217662.  904729.]
SP
[246903. 316480. 632552. 336688. 168923.]
SPAR
[149813. 222535. 352625. 233423. 177236.]
SPCB
[1114214. 1228091. 2373058. 4247630. 1363044.]
SPFI
[12546. 11617.  6115. 13355. 23853.]
SPI
[ 78545. 104478.  79957.  61629.  88388.]
SPKE
[106198. 125059.  93286.  81832.  93077.]
SPKEP
[18237.  7687. 19799. 19887.  6223.]
SPLK
[1800506.  862202. 1014412. 1640184. 1760623.]
SPNE
[204958. 224252. 144346. 206923. 150291.]
SPNS
[ 48697. 113180. 109205. 130074.  63253.]
SPOK
[ 48143.  95244. 132626.  88727.  93080.]
SPPI
[ 765613.  891526. 1645508. 1186814. 1419493.]
SPRO
[ 97847. 127744.  48005.  65367. 114574.]
SPRT
[ 53820.  77042.  66709.  79517. 212685.]
SPSC
[283082. 250856. 193561. 282226. 223909.]
SPT
[199571. 151069. 230156. 320142. 278410.]
SPTN
[268724. 416887. 411796. 532397. 408754.]
SPWH
[399282. 366562. 550909. 489638. 425171.]
SPWR
[3563917. 2639241. 3590000. 4596363. 4814412.]
SQBG
[

THMO
[3090204. 1810200. 1352002.  835656. 2246688.]
THRM
[156251. 129547. 153788. 152086. 198073.]
THTX
[ 93182. 107634. 177856. 131961. 367525.]
THWWW
[15440.  3719.   900.  3168.   100.]
TIGO
[ 55801.  74448. 104264.  47778.  81436.]
TIGR
[101828.  70554. 110107. 188532. 196090.]
TILE
[219797. 437652. 512447. 322266. 209523.]
TIPT
[126094.  55847.  48820.  40286.  44425.]
TITN
[123050. 214389. 193327. 195400. 140700.]
TIVO
[ 435153. 1450298.  443841.  454277.  553093.]
TLC
[ 435. 2934. 1707. 5244. 2069.]
TLF
[ 5027. 27806.  8883.  1401.   702.]
TLGT
[125550. 199185. 161205. 158760. 367311.]
TLND
[103438.  92535. 122149. 367212. 133240.]
TLRY
[20323250.  7693018.  5949974.  8420551. 12945450.]
TLSA
[417350. 104389. 107478. 179665. 182401.]
TLT
[14260806. 10147077. 13811848.  9434786.  6570840.]
TMDI
[ 348797.  514026.  311995.  695103. 1929518.]
TMDX
[50876. 70484. 98880. 82693. 90229.]
TMSR
[18487. 29354. 22484. 86565.  8406.]
TMUS
[3511436. 4537354. 4261904. 3946374. 3508714.]
TNAV


VERI
[161130. 337322. 261033. 228525. 588805.]
VERO
[15524.  2255.  8542. 13170.  9815.]
VERU
[275317. 329721. 128836.  72800. 136069.]
VERY
[ 76. 143. 712.  36. 385.]
VETS
[ 15.   7.   0. 620.  15.]
VFF
[600106. 611944. 289635. 512185. 775347.]
VG
[2307112. 2803776. 7067615. 2518871. 3821105.]
VGIT
[ 702146.  494890.  525073. 1215472.  905947.]
VGLT
[411269. 184732. 317452. 290700. 659264.]
VGSH
[2368335. 2239060. 2518860. 2751125. 2000459.]
VIAC
[11001375. 10601223.  8514394.  7964104.  7836186.]
VIACA
[117412. 111951.  88960. 158575.  57843.]
VIAV
[1274574. 2023765. 1743163. 1633510. 1719191.]
VICR
[458016. 217254. 163312. 112995. 164897.]
VIE
[ 31361.  89446.  31855. 160472. 113161.]
VIGI
[380420. 387221. 386182. 585232. 225462.]
VIIX
[12171. 14939. 18527. 58435. 28716.]
VIOT
[ 67633.  75499. 114511. 378139. 131475.]
VIR
[1787107. 1580175. 1040047. 1523685. 1833142.]
VIRC
[ 305.  136.  181. 3337.  847.]
VIRT
[622234. 731845. 508092. 763948. 899323.]
VISL
[6216796. 4105673. 4659667.

XT
[219292. 237605. 172613. 144642. 198441.]
XTLB
[ 156.  207. 1037. 8157.  248.]
YGYI
[202137. 145066. 164235. 365798. 337547.]
YGYIP
[6105.  188. 1937. 1365.  862.]
YI
[ 39229.  58955.   5574.  35429. 104168.]
YIN
[ 6008. 12585.  5132.  5033.  1035.]
YJ
[ 29046.  48281.  41143.  51391. 111939.]
YLCO
[10153.  5743. 26440. 32228. 48942.]
YLDE
[1.9603e+04 6.3600e+02 0.0000e+00 9.0000e+00 3.6070e+03]
YMAB
[202933. 155659. 148992. 154474. 168378.]
YNDX
[1669492. 1095629. 1896122. 4170287. 3854840.]
YORW
[37301. 36434. 31801. 21716. 34434.]
YRCW
[2704660. 1499762. 1523465. 1012427. 1988189.]
YTEN
[ 38337. 102211.  67355.  40428.  29753.]
YTRA
[ 786626.  480217.  365770. 1808460.  124288.]
YVR
[108710.  66820.  90878. 205063.  82668.]
YY
[603074. 487392. 638007. 900388. 868657.]
Z
[3078100. 2737050. 3137566. 1827042. 2327870.]
ZAGG
[562581. 489644. 675799. 522144. 538090.]
ZAZZT
[100. 100. 100. 100. 100.]
ZBRA
[418500. 436891. 498841. 379183. 381535.]
ZBZZT
[100. 100. 100. 100. 100.]
ZCMD
[

FileNotFoundError: [Errno 2] File Stock_CSV/ZUMZ.csv does not exist: 'Stock_CSV/ZUMZ.csv'

In [65]:
#days = ['M', 'T', 'W', 'Th', 'F']
#numbers = [1,2,3,4,5]

#plt.bar(days, numbers)
#plt.title('Average Volume per Day in Past Month for '+ stock)
#plt.xlabel('Days')
#plt.ylabel('Volume')
#plt.show()
