In [1]:
#Install the dependencies
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib. pyplot as plt

In [2]:
## stock list to iterate through
stock_list = ['AAPL','ABBV','ABT','ACN','AGN','AIG','ALL','AMGN','AMZN','BA','BAC','BIIB','BK','BKNG',
              'BMY','BRK.B','C','CAT','CHTR','CMCSA','COF','COST','CSCO','CVS','DD','DHR','DIS',
                'DOW','DUK','EXC','F','FB','FDX','GD','GILD','GM','GOOG','GOOGL','GS','HON','IBM',
                'INTC','JNJ','JPM','KMI','KO','LLY','LMT','LOW','MCD','MDLZ','MDT','MET','MMM','MRK',
                'MS','MSFT','NEE','NFLX','NVDA','ORCL','OXY','PEP','PFE','PM','PYPL','QCOM','RTN','SBUX',
                'SO','SPG','T','TGT','TMO','UNH','UNP','UPS','USB','UTX','VZ','WBA','WFC','WMT','XOM']

In [6]:
manual_list = ['AAPL','ABBV','ABT','ACN','AGN','AIG','ALL','AMGN','AMZN','BA','BAC','BIIB','BK','BKNG',
              'BMY','BRK.B','C','CAT','CHTR','CMCSA','COF','COST','CSCO','CVS','DD','DHR','DIS',
                'DOW','DUK','EXC','F','FB','FDX','GD','GILD','GM','GOOG','GOOGL','GS','HON','IBM',
                'INTC','JNJ','JPM','KMI','KO','LLY','LMT','LOW','MCD','MDLZ','MDT','MET','MMM','MRK',
                'MS','MSFT','NEE','NFLX','NVDA','ORCL','OXY','PEP','PFE','PM','PYPL','QCOM','RTN','SBUX',
                'SO','SPG','T','TGT','TMO','UNH','UNP','UPS','USB','UTX','VZ','WBA','WFC','WMT','XOM']

In [23]:
man_list_tester = []
for manual in manual_list:
    print(manual)
    df = pd.read_csv("moving average tests/stock_csv_avg_test/" + stock + '.csv') 
    df= df[['5. volume']]
    vol_test = df.iloc[0:5].values
    man_result = vol_test.ravel() 
    print(man_result)
    man_list_tester.append(man_result)
    
print(man_list_tester)



comp_gen_list = []
#plt.clf()
for stock in stock_list:
    print(stock)
    df = pd.read_csv("moving average tests/stock_csv_avg_test/" + stock + '.csv') 
    df= df[['5. volume']]
    volumes = df.iloc[0:5].values
    result = volumes.ravel() 
    print(result)
    comp_gen_list.append(result)
    
print(comp_gen_list)

total = len(comp_gen_list)
count_correct = 0
for i in range(len(comp_gen_list)):
    if man_list_tester[i].all() == comp_gen_list[i].all():
        print(True)
        count_correct += 1
    else: 
        print(False)
        
#printing counted correct over total stocks in list
print("Accuracy Test for all S&P Stocks:", count_correct/total*100, '%')
    
    

AAPL
[51550947. 46717092. 56533649. 61774908. 56893766.]
ABBV
[51550947. 46717092. 56533649. 61774908. 56893766.]
ABT
[51550947. 46717092. 56533649. 61774908. 56893766.]
ACN
[51550947. 46717092. 56533649. 61774908. 56893766.]
AGN
[51550947. 46717092. 56533649. 61774908. 56893766.]
AIG
[51550947. 46717092. 56533649. 61774908. 56893766.]
ALL
[51550947. 46717092. 56533649. 61774908. 56893766.]
AMGN
[51550947. 46717092. 56533649. 61774908. 56893766.]
AMZN
[51550947. 46717092. 56533649. 61774908. 56893766.]
BA
[51550947. 46717092. 56533649. 61774908. 56893766.]
BAC
[51550947. 46717092. 56533649. 61774908. 56893766.]
BIIB
[51550947. 46717092. 56533649. 61774908. 56893766.]
BK
[51550947. 46717092. 56533649. 61774908. 56893766.]
BKNG
[51550947. 46717092. 56533649. 61774908. 56893766.]
BMY
[51550947. 46717092. 56533649. 61774908. 56893766.]
BRK.B
[51550947. 46717092. 56533649. 61774908. 56893766.]
C
[51550947. 46717092. 56533649. 61774908. 56893766.]
CAT
[51550947. 46717092. 56533649. 61774908.

[2662532. 3563458. 3539566. 3197448. 3181080.]
AMGN
[4119780. 5162547. 5301004. 5288247. 4396603.]
AMZN
[5387897. 6235118. 6479073. 7147080. 7808489.]
BA
[47729982. 63172068. 77314766. 42870185. 45885390.]
BAC
[9.14156170e+07 1.16044233e+08 1.46780467e+08 1.47475263e+08
 1.81381030e+08]
BIIB
[1653113. 2270494. 2678911. 3464065. 2695449.]
BK
[5764473. 8440925. 9866627. 9411081. 8554646.]
BKNG
[701507. 616548. 998892. 853989. 859891.]
BMY
[14494812. 21599571. 20918294. 16481668. 21234344.]
BRK.B
[10258794. 14126526. 13842256. 14063092. 16499448.]
C
[25471653. 31526377. 38185069. 34051238. 32982636.]
CAT
[5745007. 6059607. 6577059. 7409740. 6734663.]
CHTR
[1909941. 2182740. 2222772. 2817736. 2462506.]
CMCSA
[27910405. 38332143. 57834084. 46492841. 38600869.]
COF
[4392095. 6025804. 5469019. 5552285. 6718990.]
COST
[4250350. 5471961. 5639577. 7124190. 5646352.]
CSCO
[31278581. 38487226. 42873923. 48235609. 39823397.]
CVS
[15031246. 23184687. 19586080. 19294581. 16321875.]
DD
[ 5996981.  862